// <auto-generated />
using LolApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LolApi.Migrations
{
    [DbContext(typeof(LolApiContext))]
    partial class LolApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("LolApi.Models.LolItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abilities");

                    b.Property<string>("Armor");

                    b.Property<string>("AttackDamage");

                    b.Property<string>("AttackSpeed");

                    b.Property<string>("ChampionName");

                    b.Property<string>("Description");

                    b.Property<string>("Health");

                    b.Property<string>("HealthRegen");

                    b.Property<string>("MagicResist");

                    b.Property<string>("MovementSpeed");

                    b.Property<string>("Tags");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("LolItem");
                });
#pragma warning restore 612, 618
        }
    }
}
